name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: [macos-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Test `make`
      run: make
    - name: Test `make re`
      run: make re
    - name: Test basic command in input
      run: echo -e "Test ligne 1\nTest ligne 2" | ./minishell
