name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: [macos-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Test `make`
      run: make
    - name: Test `make re`
      run: make re
    - name: Test basic command in input
      run: echo -e "ls;ls -la; error; cat Makefile ; env \n ls -la ; export a=a ; env ; export" | ./minishell
    - name: Unit tests
      run: make test
